version: '3.9'

services:
  demo-db:
    image: postgres:17.5-alpine
    container_name: demo-db
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - spring-boot-advanced-demo

  demo-service:
    build:
      context: .
    container_name: demo-service
    environment:
      - spring.profiles.active=prod
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "8080:8080"
      - "1010:1010"
    depends_on:
      - demo-db
    networks:
      - spring-boot-advanced-demo

  prometheus:
    image: prom/prometheus:v2.55.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    depends_on:
      - demo-service
    networks:
      - spring-boot-advanced-demo

  grafana:
    image: grafana/grafana:11.6.1
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - spring-boot-advanced-demo

volumes :
  prometheus-data :
  grafana-data:
  pgdata:

networks:
  spring-boot-advanced-demo:
    driver: bridge
