services:
  demo-db:
    image: postgres:17.5-alpine
    container_name: demo-db
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
    ports:
      - "5433:5432"

  demo-service:
    build:
      context: .
    container_name: demo-service
    environment:
      - spring.profiles.active=prod
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - demo-db
