spring:
  application:
    name: demo
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    csrf:
      enabled: false
  jwt:
    secret: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
    expiration: 3600000

management:
  server:
    port: 1010
  metrics:
    export:
      defaults:
        enabled: true
      prometheus:
        enabled: true
    endpoint:
      metrics:
        enabled: true
    enabled: true
    tags:
      application: ${spring.application.name}
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health,beans,info,env,flyway,metrics,prometheus
  endpoint:
    health:
      show-details: always

server:
  port: 8080
