spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres_db
    username: postgres_user
    password: postgres_password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    csrf:
      enabled: false
  jwt:
    secret: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
    expiration: 3600000

management:
  server:
    port: 1010
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health,beans,info,env,flyway,metrics
  endpoint:
    health:
      show-details: always

server:
  port: 8080
